---
x-defaults: &defaults
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true
services:
  cod4x:
    <<: *defaults
    platform: linux/386
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "2"
    user: 1000:1000
    restart: unless-stopped
    build: .
    ports:
      - 28960:28960/udp
    volumes:
      - ./server:/home/cod4x/server:ro
